-- Arcadia Mobile Supabase schema.
-- Run in the Supabase SQL editor. Keep service-role credentials server-side.

create extension if not exists "pgcrypto";

create table public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  phone text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  brand text not null,
  sku text unique,
  description text,
  price numeric(12, 2) not null check (price >= 0),
  old_price numeric(12, 2) check (old_price is null or old_price >= price),
  condition text,
  storage text,
  color text,
  warranty text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  alt_text text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.inventory (
  product_id bigint primary key references public.products(id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid references public.users(id) on delete set null,
  customer_name text not null,
  phone text not null,
  email text not null,
  state text not null,
  city text not null,
  address text not null,
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  delivery_fee numeric(12, 2) not null default 0 check (delivery_fee >= 0),
  total numeric(12, 2) not null check (total >= 0),
  status text not null default 'Pending' check (status in ('Pending', 'Confirmed', 'Processing', 'Shipped', 'Delivered', 'Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0)
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  method text not null,
  reference text unique,
  amount numeric(12, 2) not null check (amount >= 0),
  status text not null default 'Pending' check (status in ('Pending', 'Paid', 'Failed', 'Refunded')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.repairs (
  id uuid primary key default gen_random_uuid(),
  repair_id text not null unique,
  user_id uuid references public.users(id) on delete set null,
  name text not null,
  phone text not null,
  email text not null,
  device text not null,
  problem text not null,
  device_details text,
  problem_details text,
  additional_information text,
  preferred_date date,
  diagnosis text,
  repair_cost numeric(12, 2) check (repair_cost is null or repair_cost >= 0),
  status text not null default 'Requested' check (status in ('Requested', 'Received', 'Diagnosing', 'Awaiting Approval', 'Repairing', 'Testing', 'Ready', 'Completed', 'Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.repair_updates (
  id uuid primary key default gen_random_uuid(),
  repair_id uuid not null references public.repairs(id) on delete cascade,
  status text not null,
  note text,
  created_at timestamptz not null default now()
);

create table public.wishlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.wishlist_items (
  wishlist_id uuid not null references public.wishlists(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (wishlist_id, product_id)
);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid references public.users(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  title text,
  body text,
  is_approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  label text,
  state text not null,
  city text not null,
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notification_preferences (
  user_id uuid primary key references public.users(id) on delete cascade,
  email_enabled boolean not null default true,
  whatsapp_enabled boolean not null default true,
  sms_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  audience text not null check (audience in ('customer', 'admin')),
  event_type text not null check (event_type in ('order_confirmation', 'payment_confirmation', 'shipping_notification', 'delivery_notification', 'repair_update', 'new_order', 'new_repair_request', 'payment_received', 'low_stock')),
  channel text not null check (channel in ('email', 'whatsapp', 'sms')),
  recipient text not null,
  subject text,
  message text not null,
  status text not null default 'Queued' check (status in ('Queued', 'Sent', 'Failed')),
  provider_reference text,
  metadata jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_idx on public.notifications(user_id, created_at desc);
create index notifications_event_idx on public.notifications(event_type, created_at desc);
alter table public.notification_preferences enable row level security;
alter table public.notifications enable row level security;
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.users where id = auth.uid() and is_admin = true); $$;

create policy "Users manage own notification preferences" on public.notification_preferences for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users read own notifications" on public.notifications for select using (user_id = auth.uid() or public.is_admin());
create policy "Admins manage notifications" on public.notifications for all using (public.is_admin()) with check (public.is_admin());

create index products_category_idx on public.products(category_id);
create index product_images_product_idx on public.product_images(product_id, sort_order);
create index orders_user_idx on public.orders(user_id, created_at desc);
create index order_items_order_idx on public.order_items(order_id);
create index repairs_user_idx on public.repairs(user_id, created_at desc);
create index repairs_lookup_idx on public.repairs(repair_id);
create index repair_updates_repair_idx on public.repair_updates(repair_id, created_at desc);
create index reviews_product_idx on public.reviews(product_id, created_at desc);
create index addresses_user_idx on public.addresses(user_id);

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.inventory enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.repairs enable row level security;
alter table public.repair_updates enable row level security;
alter table public.wishlists enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.reviews enable row level security;
alter table public.addresses enable row level security;

create policy "Public can read active catalog" on public.products for select using (is_active = true or public.is_admin());
create policy "Public can read categories" on public.categories for select using (true);
create policy "Public can read product images" on public.product_images for select using (true);
create policy "Public can read inventory" on public.inventory for select using (true);
create policy "Admins manage catalog" on public.products for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage product images" on public.product_images for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage inventory" on public.inventory for all using (public.is_admin()) with check (public.is_admin());
create policy "Users read own orders" on public.orders for select using (user_id = auth.uid() or public.is_admin());
create policy "Users read own order items" on public.order_items for select using (exists (select 1 from public.orders where orders.id = order_id and (orders.user_id = auth.uid() or public.is_admin())));
create policy "Users read own repairs" on public.repairs for select using (user_id = auth.uid() or public.is_admin());
create policy "Users read repair updates" on public.repair_updates for select using (exists (select 1 from public.repairs where repairs.id = repair_id and (repairs.user_id = auth.uid() or public.is_admin())));
create policy "Admins manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage payments" on public.payments for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage repairs" on public.repairs for all using (public.is_admin()) with check (public.is_admin());
create policy "Admins manage repair updates" on public.repair_updates for all using (public.is_admin()) with check (public.is_admin());
create policy "Users manage own addresses" on public.addresses for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users manage own wishlists" on public.wishlists for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users manage own wishlist items" on public.wishlist_items for all using (exists (select 1 from public.wishlists where wishlists.id = wishlist_id and wishlists.user_id = auth.uid())) with check (exists (select 1 from public.wishlists where wishlists.id = wishlist_id and wishlists.user_id = auth.uid()));
create policy "Public can read approved reviews" on public.reviews for select using (is_approved = true or user_id = auth.uid() or public.is_admin());
create policy "Users create own reviews" on public.reviews for insert with check (user_id = auth.uid());
create policy "Admins manage reviews" on public.reviews for all using (public.is_admin()) with check (public.is_admin());
create policy "Users read own profile" on public.users for select using (id = auth.uid() or public.is_admin());
create policy "Users create own profile" on public.users for insert with check (id = auth.uid());
create policy "Admins manage users" on public.users for all using (public.is_admin()) with check (public.is_admin());

create or replace function public.calculate_delivery_fee(delivery_state text, delivery_city text)
returns numeric
language plpgsql
immutable
as $$
declare
  normalized_state text := lower(trim(coalesce(delivery_state, '')));
  normalized_city text := lower(trim(coalesce(delivery_city, '')));
begin
  if normalized_state in ('plateau', 'plateau state') then
    if normalized_city like '%jos north%' then return 2000; end if;
    if normalized_city like '%rayfield%' then return 2500; end if;
    if normalized_city = 'jos' or normalized_city like 'jos %' then return 2000; end if;
    return 3000;
  end if;
  if normalized_state = 'lagos' or normalized_city = 'lagos' then return 5000; end if;
  if normalized_state = 'abuja' or normalized_city = 'abuja' then return 5000; end if;
  if normalized_state = 'kaduna' or normalized_city = 'kaduna' then return 5000; end if;
  if normalized_state = 'kano' or normalized_city = 'kano' then return 5500; end if;
  if normalized_state in ('rivers', 'port harcourt') or normalized_city = 'port harcourt' then return 5500; end if;
  return 0;
end;
$$;

create or replace function public.create_verified_order(order_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_year text := to_char(current_date, 'YYYY');
  next_sequence integer;
  new_order public.orders;
  requested_item jsonb;
  product_row public.products;
  calculated_subtotal numeric(12, 2) := 0;
  item_quantity integer;
  delivery_fee numeric(12, 2);
begin
  perform pg_advisory_xact_lock(hashtext('arcadia-order-number-' || current_year));
  delivery_fee := public.calculate_delivery_fee(order_payload->'delivery'->>'state', order_payload->'delivery'->>'city');

  select coalesce(max((split_part(order_number, '-', 3))::integer), 0) + 1
    into next_sequence
    from public.orders
   where order_number like 'ARC-' || current_year || '-%';

  for requested_item in select * from jsonb_array_elements(order_payload->'items') loop
    select * into product_row from public.products where id = (requested_item->>'id')::bigint and is_active = true for update;
    item_quantity := (requested_item->>'quantity')::integer;
    if product_row.id is null or item_quantity is null or item_quantity < 1 then
      raise exception 'Invalid product in order';
    end if;
    if not exists (select 1 from public.inventory where product_id = product_row.id and quantity >= item_quantity) then
      raise exception 'Insufficient inventory';
    end if;
    calculated_subtotal := calculated_subtotal + (product_row.price * item_quantity);
  end loop;

  if calculated_subtotal + delivery_fee <> (order_payload->>'verified_amount')::numeric then
    raise exception 'Verified payment amount does not match order total';
  end if;

  insert into public.orders (order_number, user_id, customer_name, phone, email, state, city, address, subtotal, delivery_fee, total, status)
  values ('ARC-' || current_year || '-' || lpad(next_sequence::text, 5, '0'), auth.uid(), order_payload->'customer'->>'name', order_payload->'customer'->>'phone', order_payload->'customer'->>'email', order_payload->'delivery'->>'state', order_payload->'delivery'->>'city', order_payload->'delivery'->>'address', calculated_subtotal, delivery_fee, calculated_subtotal + delivery_fee, 'Processing')
  returning * into new_order;

  for requested_item in select * from jsonb_array_elements(order_payload->'items') loop
    select * into product_row from public.products where id = (requested_item->>'id')::bigint;
    item_quantity := (requested_item->>'quantity')::integer;
    insert into public.order_items (order_id, product_id, product_name, unit_price, quantity)
    values (new_order.id, product_row.id, product_row.name, product_row.price, item_quantity);
    update public.inventory set quantity = quantity - item_quantity, updated_at = now() where product_id = product_row.id;
  end loop;

  insert into public.payments (order_id, method, reference, amount, status)
  values (new_order.id, order_payload->>'payment_method', order_payload->>'reference', new_order.total, 'Paid');

  return to_jsonb(new_order);
end;
$$;
